<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Model>
 */
class TransactionFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'business_id' => fake()->randomNumber(),
            'location_id' => fake()->randomNumber(),
            'res_table_id' => fake()->randomNumber(),
            'res_waiter_id' => fake()->randomNumber(),
            'res_order_status' => fake()->randomElement(['received','cooked','served']),
            'type' => fake()->text(191),
            'sub_type' => fake()->text(20),
            'status' => fake()->text(191),
            'sub_status' => fake()->text(191),
            'is_quotation' => fake()->boolean(),
            'payment_status' => fake()->randomElement(['paid','due','partial']),
            'adjustment_type' => fake()->randomElement(['normal','abnormal']),
            'contact_id' => fake()->randomNumber(),
            'customer_group_id' => fake()->randomNumber(),
            'invoice_no' => fake()->text(191),
            'ref_no' => fake()->text(191),
            'source' => fake()->text(191),
            'subscription_no' => fake()->text(191),
            'subscription_repeat_on' => fake()->text(191),
            'transaction_date' => fake()->dateTime(),
            'total_before_tax' => fake()->randomFloat(4, 0, 999999999999999999),
            'tax_id' => fake()->randomNumber(),
            'tax_amount' => fake()->randomFloat(4, 0, 999999999999999999),
            'discount_type' => fake()->randomElement(['fixed','percentage']),
            'discount_amount' => fake()->randomFloat(4, 0, 999999999999999999),
            'rp_redeemed' => fake()->randomNumber(),
            'rp_redeemed_amount' => fake()->randomFloat(4, 0, 999999999999999999),
            'shipping_details' => fake()->text(191),
            'shipping_address' => fake()->paragraph(),
            'delivery_date' => fake()->dateTime(),
            'shipping_status' => fake()->text(191),
            'delivered_to' => fake()->text(191),
            'shipping_charges' => fake()->randomFloat(4, 0, 999999999999999999),
            'shipping_custom_field_1' => fake()->text(191),
            'shipping_custom_field_2' => fake()->text(191),
            'shipping_custom_field_3' => fake()->text(191),
            'shipping_custom_field_4' => fake()->text(191),
            'shipping_custom_field_5' => fake()->text(191),
            'additional_notes' => fake()->paragraph(),
            'staff_note' => fake()->paragraph(),
            'is_export' => fake()->boolean(),
            'export_custom_fields_info' => fake()->paragraph(),
            'round_off_amount' => fake()->randomFloat(4, 0, 999999999999999999),
            'additional_expense_key_1' => fake()->text(191),
            'additional_expense_value_1' => fake()->randomFloat(4, 0, 999999999999999999),
            'additional_expense_key_2' => fake()->text(191),
            'additional_expense_value_2' => fake()->randomFloat(4, 0, 999999999999999999),
            'additional_expense_key_3' => fake()->text(191),
            'additional_expense_value_3' => fake()->randomFloat(4, 0, 999999999999999999),
            'additional_expense_key_4' => fake()->text(191),
            'additional_expense_value_4' => fake()->randomFloat(4, 0, 999999999999999999),
            'final_total' => fake()->randomFloat(4, 0, 999999999999999999),
            'expense_category_id' => fake()->randomNumber(),
            'expense_sub_category_id' => fake()->randomNumber(),
            'expense_for' => fake()->randomNumber(),
            'commission_agent' => fake()->randomNumber(),
            'document' => fake()->text(191),
            'is_direct_sale' => fake()->boolean(),
            'is_suspend' => fake()->boolean(),
            'exchange_rate' => fake()->randomFloat(3, 0, 99999999999999999),
            'total_amount_recovered' => fake()->randomFloat(4, 0, 999999999999999999),
            'transfer_parent_id' => fake()->randomNumber(),
            'return_parent_id' => fake()->randomNumber(),
            'opening_stock_product_id' => fake()->randomNumber(),
            'created_by' => fake()->randomNumber(),
            'purchase_requisition_ids' => fake()->paragraph(),
            'prefer_payment_method' => fake()->text(191),
            'prefer_payment_account' => fake()->randomNumber(),
            'sales_order_ids' => fake()->paragraph(),
            'purchase_order_ids' => fake()->paragraph(),
            'custom_field_1' => fake()->text(191),
            'custom_field_2' => fake()->text(191),
            'custom_field_3' => fake()->text(191),
            'custom_field_4' => fake()->text(191),
            'import_batch' => fake()->randomNumber(),
            'import_time' => fake()->dateTime(),
            'types_of_service_id' => fake()->randomNumber(),
            'packing_charge' => fake()->randomFloat(4, 0, 999999999999999999),
            'packing_charge_type' => fake()->randomElement(['fixed','percent']),
            'service_custom_field_1' => fake()->paragraph(),
            'service_custom_field_2' => fake()->paragraph(),
            'service_custom_field_3' => fake()->paragraph(),
            'service_custom_field_4' => fake()->paragraph(),
            'service_custom_field_5' => fake()->paragraph(),
            'service_custom_field_6' => fake()->paragraph(),
            'is_created_from_api' => fake()->boolean(),
            'essentials_duration' => fake()->randomFloat(2, 0, 999999),
            'essentials_duration_unit' => fake()->text(20),
            'essentials_amount_per_unit_duration' => fake()->randomFloat(4, 0, 999999999999999999),
            'essentials_allowances' => fake()->paragraph(),
            'essentials_deductions' => fake()->paragraph(),
            'rp_earned' => fake()->randomNumber(),
            'order_addresses' => fake()->paragraph(),
            'is_recurring' => fake()->boolean(),
            'recur_interval' => fake()->randomFloat(),
            'recur_interval_type' => fake()->randomElement(['days','months','years']),
            'recur_repetitions' => fake()->randomNumber(),
            'recur_stopped_on' => fake()->dateTime(),
            'recur_parent_id' => fake()->randomNumber(),
            'invoice_token' => fake()->text(191),
            'pay_term_number' => fake()->randomNumber(),
            'pay_term_type' => fake()->randomElement(['days','months']),
            'selling_price_group_id' => fake()->randomNumber(),
            'delivery_person' => fake()->numerify(),
            'created_at' => fake()->unixTime(),
            'updated_at' => fake()->unixTime(),
            'is_kitchen_order' => fake()->boolean(),
        ];
    }
}
