<?php

namespace App\Observers;

use App\Models\Booking;
use App\Models\Invoice;
use App\Models\Setting;
use App\Services\BookingService;
use App\Services\DteService;
use Illuminate\Support\Facades\Log;

class BookingObserver
{
    public function __construct(
        private readonly BookingService $bookingService,
        private readonly DteService $dteService,
    ) {
    }

    public function created(Booking $booking): void
    {
        $invoice = $this->createInvoiceIfNeeded($booking);

        if ($booking->status === Booking::STATUS_CONFIRMED) {
            $this->bookingService->notifyConfirmation($booking);
            $this->tryAutoGenerateDte($invoice);
        }
    }

    public function updated(Booking $booking): void
    {
        if (! $booking->wasChanged('status')) {
            return;
        }

        $invoice = $this->createInvoiceIfNeeded($booking);

        if ($booking->status === Booking::STATUS_CONFIRMED) {
            $this->bookingService->notifyConfirmation($booking);
            $this->tryAutoGenerateDte($invoice);
        }
    }

    private function createInvoiceIfNeeded(Booking $booking): ?Invoice
    {
        if ($booking->status !== Booking::STATUS_CONFIRMED) {
            return null;
        }

        [$invoice] = [Invoice::firstOrCreate(
            ['booking_id' => $booking->id],
            [
                'amount'     => $booking->total_price,
                'status'     => 'pending',
                'dte_status' => Invoice::DTE_NOT_GENERATED,
                'dte_code'   => null,
                'issued_at'  => now(),
            ]
        )];

        return $invoice;
    }

    /**
     * Si la configuración tiene `dte_auto_generate = true`, genera el DTE
     * automáticamente al confirmar el booking. Los errores se registran en
     * el log pero no interrumpen el flujo principal.
     */
    private function tryAutoGenerateDte(?Invoice $invoice): void
    {
        if (! $invoice) {
            return;
        }

        $dteConfig   = json_decode(optional(Setting::where('key', 'dte')->first())->value ?? '{}', true);
        $autoGenerate = (bool) ($dteConfig['dte_auto_generate'] ?? false);
        $dteEnabled   = (bool) ($dteConfig['dte_enabled'] ?? false);

        if (! $dteEnabled || ! $autoGenerate) {
            return;
        }

        try {
            $this->dteService->processDte($invoice);
        } catch (\Throwable $e) {
            Log::warning('DTE auto-generación fallida', [
                'invoice_id' => $invoice->id,
                'error'      => $e->getMessage(),
            ]);
            // No relanzar — el DTE puede generarse manualmente desde el admin
        }
    }
}
