<?php

namespace App\Observers;

use App\Jobs\TransmitInvoiceDte;
use App\Models\Booking;
use App\Models\Invoice;
use App\Models\PaymentLink;
use App\Services\BookingService;
use App\Services\Dte\DteConfig;

class BookingObserver
{
    public function __construct(
        private readonly BookingService $bookingService,
    ) {}

    public function created(Booking $booking): void
    {
        $invoice = $this->createInvoiceIfNeeded($booking);

        if ($booking->status === Booking::STATUS_CONFIRMED) {
            $this->bookingService->notifyConfirmation($booking);
            $this->tryAutoGenerateDte($invoice);
        }
    }

    /**
     * `payments` es polimórfico y no puede tener clave foránea: si la reserva se
     * borra sin limpiarlos, quedan pagos apuntando a una reserva inexistente.
     * `booking_messages` y `transport_booking_details` sí cascadean por FK.
     */
    public function deleting(Booking $booking): void
    {
        // Los enlaces cascadean por FK al borrar el pago, pero una cascada de la
        // base de datos no dispara eventos de Eloquent y dejaría los comprobantes
        // subidos por el cliente huérfanos en disco. Se borran uno a uno para que
        // MediaLibrary se lleve también los ficheros.
        PaymentLink::query()
            ->whereIn('payment_id', $booking->payments()->select('id'))
            ->get()
            ->each
            ->delete();

        $booking->payments()->delete();
    }

    public function updated(Booking $booking): void
    {
        if (! $booking->wasChanged('status')) {
            return;
        }

        $invoice = $this->createInvoiceIfNeeded($booking);

        if ($booking->status === Booking::STATUS_CONFIRMED) {
            $this->bookingService->notifyConfirmation($booking);
            $this->tryAutoGenerateDte($invoice);
        }
    }

    private function createInvoiceIfNeeded(Booking $booking): ?Invoice
    {
        if ($booking->status !== Booking::STATUS_CONFIRMED) {
            return null;
        }

        [$invoice] = [Invoice::firstOrCreate(
            ['booking_id' => $booking->id],
            [
                'amount' => $booking->total_price,
                'currency_code' => $booking->currency_code,
                'status' => 'pending',
                'dte_status' => Invoice::DTE_NOT_GENERATED,
                'issued_at' => now(),
            ]
        )];

        return $invoice;
    }

    /**
     * Con `dte_auto_generate`, el DTE se emite al confirmar la reserva. Se
     * despacha después de la respuesta: la confirmación (o el webhook de la
     * pasarela) no espera al Ministerio de Hacienda.
     */
    private function tryAutoGenerateDte(?Invoice $invoice): void
    {
        if (! $invoice) {
            return;
        }

        $config = DteConfig::load();

        if (! $config->enabled() || ! $config->autoGenerate()) {
            return;
        }

        TransmitInvoiceDte::dispatchAfterResponse($invoice);
    }
}
