<?php

namespace App\Observers;

use App\Models\Booking;
use App\Models\Invoice;
use App\Models\Setting;
use App\Services\BookingService;
use App\Services\DteService;
use Illuminate\Support\Facades\Log;

class BookingObserver
{
    public function __construct(
        private readonly BookingService $bookingService,
        private readonly DteService $dteService,
    ) {}

    public function created(Booking $booking): void
    {
        $invoice = $this->createInvoiceIfNeeded($booking);

        if ($booking->status === Booking::STATUS_CONFIRMED) {
            $this->bookingService->notifyConfirmation($booking);
            $this->tryAutoGenerateDte($invoice);
        }
    }

    /**
     * `payments` es polimórfico y no puede tener clave foránea: si la reserva se
     * borra sin limpiarlos, quedan pagos apuntando a una reserva inexistente.
     * `booking_messages` y `transport_booking_details` sí cascadean por FK.
     */
    public function deleting(Booking $booking): void
    {
        $booking->payments()->delete();
    }

    public function updated(Booking $booking): void
    {
        if (! $booking->wasChanged('status')) {
            return;
        }

        $invoice = $this->createInvoiceIfNeeded($booking);

        if ($booking->status === Booking::STATUS_CONFIRMED) {
            $this->bookingService->notifyConfirmation($booking);
            $this->tryAutoGenerateDte($invoice);
        }
    }

    private function createInvoiceIfNeeded(Booking $booking): ?Invoice
    {
        if ($booking->status !== Booking::STATUS_CONFIRMED) {
            return null;
        }

        [$invoice] = [Invoice::firstOrCreate(
            ['booking_id' => $booking->id],
            [
                'amount' => $booking->total_price,
                'currency_code' => $booking->currency_code,
                'status' => 'pending',
                'dte_status' => Invoice::DTE_NOT_GENERATED,
                'issued_at' => now(),
            ]
        )];

        return $invoice;
    }

    /**
     * Si la configuración tiene `dte_auto_generate = true`, genera el DTE
     * automáticamente al confirmar el booking. Los errores se registran en
     * el log pero no interrumpen el flujo principal.
     */
    private function tryAutoGenerateDte(?Invoice $invoice): void
    {
        if (! $invoice) {
            return;
        }

        $dteConfig = json_decode(optional(Setting::where('key', 'dte')->first())->value ?? '{}', true);
        $autoGenerate = (bool) ($dteConfig['dte_auto_generate'] ?? false);
        $dteEnabled = (bool) ($dteConfig['dte_enabled'] ?? false);

        if (! $dteEnabled || ! $autoGenerate) {
            return;
        }

        try {
            $this->dteService->processDte($invoice);
        } catch (\Throwable $e) {
            Log::warning('DTE auto-generación fallida', [
                'invoice_id' => $invoice->id,
                'error' => $e->getMessage(),
            ]);
            // No relanzar — el DTE puede generarse manualmente desde el admin
        }
    }
}
