<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class InvoiceLayout extends Model
{
    use HasFactory;

    protected $fillable = [
        'business_id',
        'name',
        'header_text',
        'invoice_no_prefix',
        'quotation_no_prefix',
        'invoice_heading',
        'sub_heading_line1',
        'sub_heading_line2',
        'sub_heading_line3',
        'sub_heading_line4',
        'sub_heading_line5',
        'invoice_heading_not_paid',
        'invoice_heading_paid',
        'quotation_heading',
        'sub_total_label',
        'discount_label',
        'tax_label',
        'total_label',
        'round_off_label',
        'total_due_label',
        'paid_label',
        'show_client_id',
        'client_id_label',
        'client_tax_label',
        'date_label',
        'date_time_format',
        'show_time',
        'show_brand',
        'show_sku',
        'show_cat_code',
        'show_expiry',
        'show_lot',
        'show_image',
        'show_sale_description',
        'sales_person_label',
        'show_sales_person',
        'table_product_label',
        'table_qty_label',
        'table_unit_price_label',
        'table_subtotal_label',
        'cat_code_label',
        'logo',
        'show_logo',
        'show_business_name',
        'show_location_name',
        'show_landmark',
        'show_city',
        'show_state',
        'show_zip_code',
        'show_country',
        'show_mobile_number',
        'show_alternate_number',
        'show_email',
        'show_tax_1',
        'show_tax_2',
        'show_barcode',
        'show_payments',
        'show_customer',
        'customer_label',
        'commission_agent_label',
        'show_commission_agent',
        'show_reward_point',
        'highlight_color',
        'footer_text',
        'module_info',
        'common_settings',
        'is_default',
        'show_qr_code',
        'qr_code_fields',
        'design',
        'cn_heading',
        'cn_no_label',
        'cn_amount_label',
        'table_tax_headings',
        'show_previous_bal',
        'prev_bal_label',
        'change_return_label',
        'product_custom_fields',
        'contact_custom_fields',
        'location_custom_fields',
        'show_letter_head',
        'letter_head',
    ];

    public function getResourceType(): string
    {
        return 'invoice-layouts';
    }

    public function business()
    {
        return $this->belongsTo(Business::class, 'business_id');
    }

    public function business_locations()
    {
        return $this->hasMany(BusinessLocation::class, 'invoice_layout_id');
    }

    protected function casts(): array
    {
        return [
            'name' => 'string',
            'invoice_no_prefix' => 'string',
            'quotation_no_prefix' => 'string',
            'invoice_heading' => 'string',
            'sub_heading_line1' => 'string',
            'sub_heading_line2' => 'string',
            'sub_heading_line3' => 'string',
            'sub_heading_line4' => 'string',
            'sub_heading_line5' => 'string',
            'invoice_heading_not_paid' => 'string',
            'invoice_heading_paid' => 'string',
            'quotation_heading' => 'string',
            'sub_total_label' => 'string',
            'discount_label' => 'string',
            'tax_label' => 'string',
            'total_label' => 'string',
            'round_off_label' => 'string',
            'total_due_label' => 'string',
            'paid_label' => 'string',
            'show_client_id' => 'boolean',
            'client_id_label' => 'string',
            'client_tax_label' => 'string',
            'date_label' => 'string',
            'date_time_format' => 'string',
            'show_time' => 'boolean',
            'show_brand' => 'boolean',
            'show_sku' => 'boolean',
            'show_cat_code' => 'boolean',
            'show_expiry' => 'boolean',
            'show_lot' => 'boolean',
            'show_image' => 'boolean',
            'show_sale_description' => 'boolean',
            'sales_person_label' => 'string',
            'show_sales_person' => 'boolean',
            'table_product_label' => 'string',
            'table_qty_label' => 'string',
            'table_unit_price_label' => 'string',
            'table_subtotal_label' => 'string',
            'cat_code_label' => 'string',
            'logo' => 'string',
            'show_logo' => 'boolean',
            'show_business_name' => 'boolean',
            'show_location_name' => 'boolean',
            'show_landmark' => 'boolean',
            'show_city' => 'boolean',
            'show_state' => 'boolean',
            'show_zip_code' => 'boolean',
            'show_country' => 'boolean',
            'show_mobile_number' => 'boolean',
            'show_alternate_number' => 'boolean',
            'show_email' => 'boolean',
            'show_tax_1' => 'boolean',
            'show_tax_2' => 'boolean',
            'show_barcode' => 'boolean',
            'show_payments' => 'boolean',
            'show_customer' => 'boolean',
            'customer_label' => 'string',
            'commission_agent_label' => 'string',
            'show_commission_agent' => 'boolean',
            'show_reward_point' => 'boolean',
            'highlight_color' => 'string',
            'is_default' => 'boolean',
            'business_id' => 'integer',
            'show_letter_head' => 'boolean',
            'letter_head' => 'string',
            'show_qr_code' => 'boolean',
            'design' => 'string',
            'cn_heading' => 'string',
            'cn_no_label' => 'string',
            'cn_amount_label' => 'string',
            'show_previous_bal' => 'boolean',
            'prev_bal_label' => 'string',
            'change_return_label' => 'string'
        ];
    }
}
